
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
    initial-size: 5
    max-active: 50
    max-wait: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        max-active: 20
        initial-size: 10
        min-idle: 8
        filter:
          stat:
            log-slow-sql: true
        stat-view-servlet:
          url-pattern: "/druid/*"
          login-username:
          login-password:
          #是否可以重置
          reset-enable: true
          #启用
          enabled: true

  # Redis数据库索引（默认为0）
  redis:
    # Redis库
    database: 1
    # Redis服务器地址
    host: 172.16.95.250
    # Redis服务器连接端口
    port: 6379
    # Redis连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 8000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 8000

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
mapper:
  notEmpty: false
  identity: MYSQL

server:
  servlet:
    context-path: /demoboot
  port: 8081

# logback日志配置
logging:
  config: classpath:logback-spring.xml

service:
  # 是否启动任务线程
  taskthread-flag: true
  # 是否启动测试线程
  testthread-flag: true
  # 启动等待时间
  test-startwaitingsecond: 5
  # 循环周期
  test-looptimersecond: 30
  # 最大等待时间
  test-totallooptimersecond: 60

# 自定义配置
token:
  effectiveTime: 7200
  secret: test_secret
  cookieName: token-test
  redisHeader: test_
  exclude:
    urls:
      - /doc
      - /usermanager/getUserCenterToken

